{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ce4c3fff",
   "metadata": {},
   "outputs": [],
   "source": [
    "from axelrod.action import Action\n",
    "from axelrod.player import Player\n",
    "class Downing2(Player):\n",
    "    \"\"\"\n",
    "    Modified version of the Downing strategy.\n",
    "\n",
    "    This strategy cooperates during the first two rounds and then applies the\n",
    "    same logic as the original Downing strategy for subsequent rounds. \n",
    "\n",
    "    For further details, see the original Downing strategy description.\n",
    "    \"\"\"\n",
    "\n",
    "    name = \"Downing2\"\n",
    "\n",
    "    classifier = {\n",
    "        \"memory_depth\": float(\"inf\"),\n",
    "        \"stochastic\": False,\n",
    "        \"long_run_time\": False,\n",
    "        \"inspects_source\": False,\n",
    "        \"manipulates_source\": False,\n",
    "        \"manipulates_state\": False,\n",
    "    }\n",
    "\n",
    "    def __init__(self) -> None:\n",
    "        super().__init__()\n",
    "        self.number_opponent_cooperations_in_response_to_C = 0\n",
    "        self.number_opponent_cooperations_in_response_to_D = 0\n",
    "\n",
    "    def strategy(self, opponent: Player) -> Action:\n",
    "        \"\"\"Actual strategy definition that determines player's action.\"\"\"\n",
    "        round_number = len(self.history) + 1\n",
    "\n",
    "        # Always cooperate for the first two rounds\n",
    "        if round_number <= 2:\n",
    "            return C\n",
    "\n",
    "        # Update response counts for subsequent rounds\n",
    "        if self.history[-2] == C and opponent.history[-1] == C:\n",
    "            self.number_opponent_cooperations_in_response_to_C += 1\n",
    "        if self.history[-2] == D and opponent.history[-1] == C:\n",
    "            self.number_opponent_cooperations_in_response_to_D += 1\n",
    "\n",
    "        # Adding 1 to cooperations for assumption that first opponent move\n",
    "        # being a response to a cooperation. See docstring for more\n",
    "        # information.\n",
    "        alpha = self.number_opponent_cooperations_in_response_to_C / (\n",
    "            self.cooperations + 1\n",
    "        )\n",
    "        # Adding 2 to defections on the assumption that the first two\n",
    "        # moves are defections, which may not be true in a noisy match\n",
    "        beta = self.number_opponent_cooperations_in_response_to_D / max(\n",
    "            self.defections, 2\n",
    "        )\n",
    "\n",
    "        R, P, S, T = self.match_attributes[\"game\"].RPST()\n",
    "        expected_value_of_cooperating = alpha * R + (1 - alpha) * S\n",
    "        expected_value_of_defecting = beta * T + (1 - beta) * P\n",
    "\n",
    "        if expected_value_of_cooperating > expected_value_of_defecting:\n",
    "            return C\n",
    "        if expected_value_of_cooperating < expected_value_of_defecting:\n",
    "            return D\n",
    "        return self.history[-1].flip()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
